### ISSUE TITLE
Crashing gnome-shell on Ubuntu 19.10

### ISSUE THREAD

**Issue by raulcraveiro** [floturcocantsee/GNOME_Run_With_Prime#1]
Hello! I just installed Ubuntu 19.10 Beta, and when I tried to open any app with "Run with Prime", it crashes the gnome-shell.

**Comment by floturcocantsee** [comment]
> Hello! I just installed Ubuntu 19.10 Beta, and when I tried to open any app with "Run with Prime", it crashes the gnome-shell.

Hello, thanks for reporting!

Did the crash occur in the Wayland or X session? Also what is the output of this log when the crash occurs:
`journalctl /usr/bin/gnome-shell`

**Comment by raulcraveiro** [comment]
It's on the X session, it closes all the open apps and restart the gnome shell.

How can I copy the output to send here? :no_mouth:

**Comment by floturcocantsee** [comment]
> It's on the X session, it closes all the open apps and restart the gnome shell.
> 
> How can I copy the output to send here?

You can export the last 300 lines of the log file to a text file with this command:
`journalctl -n 300 /usr/bin/gnome-shell > gnome_log.txt`

**Comment by raulcraveiro** [comment]
Here it is!

[gnome_log.txt](https://github.com/floturcocantsee/GNOME_Run_With_Prime/files/3703966/gnome_log.txt)

**Comment by floturcocantsee** [comment]
> Here it is!
> 
> [gnome_log.txt](https://github.com/floturcocantsee/GNOME_Run_With_Prime/files/3703966/gnome_log.txt)

This commit: (https://github.com/floturcocantsee/GNOME_Run_With_Prime/commit/8aa33f653b5948fd1c87d7a7ba5fb67d72cb1697) fixes this issue.
There is a bug with GNOME 3.34 where using the spawnApp function in GJS causes a system crash. Luckily trySpawn which does the same thing isn't affected. I'll compile and upload the latest change to GNOME extensions.

**Comment by floturcocantsee** [comment]
Checking the environment variables of the terminal when running in an Eoan VM shows that these fixes let the PRIME environment set correctly. Thanks for bringing this to my attention as it didn't affect GNOME 3.28 on Ubuntu 18.04. Let me know if you have any questions. Closing.
