### ISSUE TITLE
"Run with PRIME" not showing on Gnome 3.36.4

### ISSUE THREAD

**Issue by mentos1386** [floturcocantsee/GNOME_Run_With_Prime#2]
Hey, i installed the extension. Logged out and back in. Yet, i can't see the item in menu when right clicking on application on Gnome Application Menu.

I'm running Manjaro (Arch based rolling release), with latest updates.

**Comment by floturcocantsee** [comment]
Gnome 3.36 added support for what this extension does built in. When you right click an application in the dash it should have an option to run with dedicated graphics processor if you have prime offloading configured correctly

**Comment by floturcocantsee** [comment]
https://gitlab.gnome.org/GNOME/gnome-shell/-/merge_requests/781

MR on Gnome's end for reference

**Comment by mentos1386** [comment]
Wow, didn't know that. That's awesome!

I was also missing `switcheroo-control` package from AUR. Installing, enabling and starting fixed it. Thanks!
